# This is a basic workflow to help you get started with Actions

name: Run API tests

# Controls when the workflow will run
on: [pull_request]

# Allows you to run this workflow manually from the Actions tab
#workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."
          
          echo "${GITHUB_WORKSPACE}"
          pwd
          
          ls -al ..
          ls -al .
          
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/actions/script.sh"

          # run script
          "${GITHUB_WORKSPACE}/.github/actions/script.sh"
